import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/share/Header";
import RightMenu from "@/components/share/RightMenu";
import Footer from "@/components/share/Footer";
import ScrollToTop from "@/components/share/ScrollToTop";
import StyledComponentsRegistry from "@/lib/AntdRegistry";

export const metadata: Metadata = {
  title: "Nhãn mác xịn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <main >
        <Header />
        <RightMenu/>
       {children}
        <ScrollToTop />
        <Footer/>
        {/* {children} */}
      </main>
  
  );
}
